### ISSUE TITLE
It is unclear how to install pyroll-from-dict

### ISSUE THREAD

**Issue by GRPlan** [pyroll-project/pyroll-from-dict#1]
pyroll-from-dict can't be installed via pip.

If using PyRolL via pyroll.basic the user has to manually add the code from GitHub to the installation directory...

As the from_dict functionality is quite useful it should be considered to add the code to pyroll.core package.

**Comment by ChRen95** [comment]
Hi @GRPlan,
we haven't published the package yet so it's not installable via pip.

**Comment by ChRen95** [comment]
Is published on PyPi, and is now installable via pip.

**Comment by axtimhaus** [comment]
Regarding adding to core: the from dict package is for now more a rough concept how one could do it. So please give feedback on usability and alternative concepts. If it has been proven, we may think about adding it to core. But for now it is likely to have breaking changes in from dict.

**Comment by ChRen95** [comment]
I wouldn't vote for changing the common constructor. I would rather use overloading in a pythonic way to include this repo.
